### ISSUE TITLE
Carrier empty

### ISSUE THREAD

**Issue by michaelbeljaars** [mayrthom/CartridgeWriter_uPrint#5]
I was able to successfully update the EEPROM using this application, however the printer reports that the carrier is empty, even though the settings on the EEPROM show that it is full (688,2582). I have rebooted the printer and also ejected and reinserted the carrier, but to no avail. 

![image](https://user-images.githubusercontent.com/28304614/140522810-76f99c47-729d-4c90-bb37-3c3fbf03f5c1.png)

**Comment by mayrthom** [comment]
So it does recognize the cartridge, but shows that the amount of material on the cartridge is empty?
The printer still works with other cartridges? 

Have you generated a new serial number, before writing the eeprom?
If the current quantity gets too low, then the chip couldn’t be written anymore.
Otherwise if the initial or current quantity is too high, it also won’t recognize the cartridge anymore, but as far as I know, this could be redone.

The Printer behaves some times a bit weird with the rewritten eeproms.

**Comment by michaelbeljaars** [comment]
> So it does recognize the cartridge, but shows that the amount of material on the cartridge is empty? The printer still works with other cartridges?
> 
> Have you generated a new serial number, before writing the eeprom? If the current quantity gets too low, then the chip couldn’t be written anymore. Otherwise if the initial or current quantity is too high, it also won’t recognize the cartridge anymore, but as far as I know, this could be redone.
> 
> The Printer behaves some times a bit weird with the rewritten eeproms.

I forgot to generate a new serial number 🤦‍♂️ Could it be that the EEPROM is now locked?
The initial and current quantity are the same as you can see (it did not run out of material).

**Comment by michaelbeljaars** [comment]
I have tried the procedure with another cartridge, this time also generating a new serial number. It worked perfectly, the cartridge now shows as 100%. 

I repeated the procedure for the first cartridge, paying attention to also generate a new serial number. Unfortunately the printer keeps reporting the cartridge as empty, even though the quantity on the cartridge indicates it to be 100%. Also the new serial number did not stick. Did I brick this cartridge? Is the EEPROM read-only now?

**Comment by mayrthom** [comment]
Yes I guess that the printer switched the eeprom to read-only, because the printer has an internal file where it stores the serial numbers and the current quantity of it. 
Also the eeprom gets set to read-only, if the material of the cartridge runs completely empty (1-2%). So make sure that the material never gets empty. This can be achieved if there's less material in the cartridge, then quantity on the chip.

**Comment by michaelbeljaars** [comment]
Would it somehow be possible to revert the EEPROM to the writable state?

**Comment by mayrthom** [comment]
As far as I know, there can be nothing done currently.
